export const ProvincesEnum = {
  AB: "Alberta",
  BC: "British Columbia",
  MB: "Manitoba",
  NB: "New Brunswick",
  NL: "Newfoundland and Labrador",
  NS: "Nova Scotia",
  NT: "Northwest Territories",
  NU: "Nunavut",
  ON: "Ontario",
  PE: "Prince Edward Island",
  QC: "Quebec",
  SK: "Saskatchewan",
  YT: "Yukon",
};

export const PropertyTypeEnum = {
  House: "House",
  Apartment: "Apartment",
  Basement: "Basement",
};

export const Amenities = [
  "Air Conditioning",
  "Balcony",
  "Swimming Pool",
  "Gym",
  "Laundry Room",
  "Parking",
  "Garden",
  "Playground",
  "Security",
  "Wi-Fi",
  "Fireplace",
  "Pet Friendly",
  "Wheelchair Accessible",
  "Elevator",
  "Heating",
  "Dishwasher",
  "Microwave",
  "Refrigerator",
  "Stove",
  "Washer/Dryer",
  "Furnished",
  "Unfurnished",
  "Smoke-Free",
  "Cable TV",
  "Hardwood Floors",
  "Storage",
  "Close to Public Transportation",
  "Close to Schools",
  "Close to Shopping",
  "Close to Parks",
];
